/*
 * This source file was generated by the Gradle 'init' task
 */
package tdd_2024_11_26;

public class App {

    public static void main(String[] args) {
        for (int i = 1; i <= 5; i++) {
            System.out.println(i + "번");
        }
    }
}
