/*
 * This source file was generated by the Gradle 'init' task
 */
package tdd_2024_11_26;

import org.junit.jupiter.api.Test;

import tdd_2024_11_26.SimpleCalculator.SimpleCalculatorTest;

class AppTest {
    @Test void appHasAGreeting() {
        SimpleCalculatorTest st = new SimpleCalculatorTest();

        st.TestPlus();
    }
}
